steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/antuk-api:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/antuk-api:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "antuk-api"
      - "--image=gcr.io/$PROJECT_ID/antuk-api:$COMMIT_SHA"
      - "--region=asia-southeast2"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=DB_HOST=db-host:latest,DB_USERNAME=db-username:latest,DB_PASSWORD=db-password:latest,DB_NAME=db-name:latest,SECRETKEY=secret-key:latest"
images:
  - "gcr.io/$PROJECT_ID/antuk-api:$COMMIT_SHA"
logging: CLOUD_LOGGING_ONLY
